<?php

namespace App\Http\Middleware;

use App\Models\User;
use App\System\Kernel\Authentication;
use App\System\Kernel\Permission;
use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Auth as AuthAlias;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Response;


class Authenticate extends Middleware
{
    public function handle($request, Closure $next, ...$guards)
    {
       // print_r(session()->all());
        $database_name = session()->get('database_name');
        config()->set("database.connections.user_database.database",$database_name);
        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }
}
