<?php

namespace App\Http\Requests\Admin;

use App\Helpers\Permalink;
use App\Http\Requests\BaseRequest;

class CategoryRequest extends BaseRequest
{
    protected $category;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function postCategory()
    {
        $this->category = $this->post();
        unset($this->category['_token']);
        $this->category["link"] = Permalink::get($this->category["name"]);
       return $this->category;
    }

    public function allCategory()
    {
       $this->category = $this->all();
       unset($this->category['_token']);
       return $this->category;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }

}
