<?php

namespace App\Http\Requests\Admin;


use App\Http\Requests\BaseRequest;

class CommentRequest extends BaseRequest
{
    protected $comment;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function postComment()
    {
        $this->comment = $this->post();
        unset($this->comment['_token']);
        return $this->comment;
    }

    public function allComment()
    {
        $this->comment = $this->all();
        unset($this->comment['_token']);
        return $this->comment;
    }

    public function rules()
    {
        parent::rules();
        return [
        ];
    }
}
