<?php


namespace App\Http\Requests\Admin;

use App\Http\Requests\BaseRequest;

class FaqRequest extends BaseRequest
{
    protected $faq;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function postFaq()
    {
        $this->faq = $this->post();
        unset($this->faq['_token']);
        return $this->faq;
    }

    public function allFaq()
    {
        $this->faq = $this->allFaq();
        unset($this->faq['_token']);
        return $this->faq;
    }

    public function rules()
    {
        return [];
    }
}
