<?php

namespace App\Http\Requests\Admin;


use App\Http\Requests\BaseRequest;

class GalleryRequest extends BaseRequest
{
    protected $gallery;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function postGallery()
    {
        $this->gallery = $this->post();
        unset($this->gallery['_token']);
        $this->gallery["created_at"] = date('Y-m-d H:i:s');
        $this->gallery["updated_at"] = date('Y-m-d H:i:s');
        return $this->gallery;
    }

    public function allGallery()
    {
        $this->gallery = $this->all();
        unset($this->gallery['_token']);
        return $this->gallery;
    }

    public function rules()
    {
        parent::rules();
        return [

        ];
    }
}