<?php

namespace App\Http\Requests\Admin;


use App\Http\Requests\BaseRequest;

class MenuRequest extends BaseRequest
{
    protected $menu;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postMenu()
    {
        $this->menu = $this->post();
        unset($this->menu['_token']);
        return $this->menu;
    }

    public function allMenu()
    {
        $this->menu = $this->all();
        unset($this->menu['_token']);
        return $this->menu;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }
}
