<?php

namespace App\Http\Requests\Admin;


use App\Http\Requests\BaseRequest;

class MultimediaRequest extends BaseRequest
{
    protected $multimedia;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postMultimedia()
    {
        $this->multimedia = $this->post();
        unset($this->multimedia['_token']);
        return $this->multimedia;
    }

    public function allMultimedia()
    {
        $this->multimedia = $this->all();
        unset($this->multimedia['_token']);
        return $this->multimedia;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }
}
