<?php

namespace App\Http\Requests\Admin;


use App\Helpers\Permalink;
use App\Http\Requests\BaseRequest;
use Illuminate\Support\Facades\Auth;

class PostRequest extends BaseRequest
{
    protected $post;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postPost()
    {
        $this->post = $this->post();
        $this->post["link"] = Permalink::get($this->post["title"]);
        $this->post["updated_at"] = date('Y-m-d H:i:s');
        unset($this->post['_token']);
        return $this->post;
    }

    public function allPost()
    {
        $this->post = $this->all();
        unset($this->post['_token']);
        return $this->post;
    }

    public function rules()
    {
        parent::rules();
        return [
            'title'=>"required|max:200|min:2"
        ];
    }
}
