<?php

namespace App\Http\Requests\Admin;


use App\Http\Requests\BaseRequest;

class SliderRequest extends BaseRequest
{
    protected $slider;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function postSlider()
    {
        $this->slider = $this->post();
        unset($this->slider['_token']);
        $this->slider["created_at"] = date('Y-m-d H:i:s');
        $this->slider["updated_at"] = date('Y-m-d H:i:s');
        return $this->slider;
    }

    public function allSlider()
    {
        $this->slider = $this->all();
        unset($this->slider['_token']);
        return $this->slider;
    }

    public function rules()
    {
        parent::rules();
        return [
            'title'=>"required|max:200|min:2"
        ];
    }
}
