<?php

namespace App\Http\Requests\Admin;

use App\Http\Requests\BaseRequest;

class TagRequest extends BaseRequest
{
    protected $tag;
    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postTag()
    {
        $this->tag = $this->post();
        unset($this->tag['_token']);
        return $this->tag;
    }

    public function allTag()
    {
        $this->tag = $this->all();
        unset($this->tag['_token']);
        return $this->tag;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }
}
