<?php

namespace App\Http\Requests\Admin;



use App\Http\Requests\BaseRequest;

class TestimonialsRequest extends BaseRequest
{
    protected $testimaonial;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postTestimonial()
    {
        $this->testimaonial = $this->post();
        unset($this->testimaonial['_token']);
        return $this->testimaonial;
    }

    public function allTestimonial()
    {
        $this->testimaonial = $this->all();
        unset($this->testimaonial['_token']);
        return $this->testimaonial;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }
}
