<?php

namespace Modules\Contact;


use App\Http\Requests\BaseRequest;

class ContactRequest extends BaseRequest
{
    protected $contact;

    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }
    public function postTestimonial()
    {
        $this->contact = $this->post();
        unset($this->contact['_token']);
        return $this->contact;
    }

    public function allTestimonial()
    {
        $this->contact = $this->all();
        unset($this->contact['_token']);
        return $this->contact;
    }

    public function rules()
    {
        parent::rules();
        return [
            'name'=>"required|max:200|min:2"
        ];
    }
}
